# Generated by Django 6.0.5 on 2026-05-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='choice_character',
            field=models.CharField(default='0', max_length=1),
            preserve_default=False,
        ),
    ]
