# Generated by Django 6.0.5 on 2026-05-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_current_level_user_incorrect_counter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='level',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
