# Generated by Django 6.0.5 on 2026-05-28 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_questions_level'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choices',
            new_name='Choice',
        ),
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='incorrect_counter',
        ),
        migrations.RemoveField(
            model_name='user',
            name='question_number',
        ),
    ]
