# Generated by Django 6.0.5 on 2026-05-28 10:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_choices_choice_rename_questions_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='level',
        ),
        migrations.AddField(
            model_name='question',
            name='duration',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='user',
            name='current_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='current_passed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='incorrect_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='times_down',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.IntegerField()),
                ('questions', models.ManyToManyField(to='core.question')),
            ],
        ),
        migrations.CreateModel(
            name='UserQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_question_started_at', models.DateTimeField(null=True)),
                ('current_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.question')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField()),
                ('submitted_at', models.DateTimeField()),
                ('is_correct', models.BooleanField()),
                ('timed_out', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question')),
                ('user_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userquiz')),
            ],
        ),
    ]
