# Generated by Django 6.0.5 on 2026-06-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_question_level_question_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_level',
            field=models.IntegerField(default=0),
        ),
    ]
